on:
  push:
     branches:
       - master

name: build

jobs:
  blogdown:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown and blogdown
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown"))'
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo(extended = TRUE, version = "0.75.1")'
      - name: Get themes
        run: git submodule update --remote
      - name: Look at files
        run: Rscript -e 'dir()'
      - name: Install academic theme
        run: Rscript -e 'blogdown::install_theme("wowchemy/starter-academic")'
      - name: Run hugo_build()
        run: Rscript -e 'blogdown::hugo_build(local = FALSE)'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
